mongodb:
  image: "mongo:3.0"
  ports:
    - "127.0.0.1:27017:27017"
  volumes:
    - /data/mongodb:/data/db
api:
  build: "."
  ports:
    - "127.0.0.1:3000:8080"
  volumes:
    - .:/code
  links:
    - "mongodb:mongodb"
